spring:
  application:
    name: agendamento
  hibernate:
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/agendamento"
    username: "postgres"
    password: "1234"
    pool-size: "30"
  key:
     rsa-public: "classpath:rsapublic.pem"
     rsa-private: "classpath:rsaprivate.pem"

